<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-TT3UMVU" failures="2" tests="2" name="IETets" time="41.721" errors="0" timestamp="2025-06-28T11:45:34 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="33.808">
    <failure type="java.lang.RuntimeException" message="❗ No data row found for scenario &amp;apos;Test login with multiple credentials&amp;apos; in sheet &amp;apos;Credentials&amp;apos;">
      <![CDATA[java.lang.RuntimeException: ❗ No data row found for scenario 'Test login with multiple credentials' in sheet 'Credentials'
at hooks.Hookss.setUp(Hookss.java:40)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="6.474">
    <failure type="java.lang.RuntimeException" message="❗ No data row found for scenario &amp;apos;Test login with invalid crdential&amp;apos; in sheet &amp;apos;InvalidCredentials&amp;apos;">
      <![CDATA[java.lang.RuntimeException: ❗ No data row found for scenario 'Test login with invalid crdential' in sheet 'InvalidCredentials'
at hooks.Hookss.setUp(Hookss.java:40)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- IETets -->
